name: plekapp
recipe: laravel

# Configure the laravel recipe
config:
  php: '7.3'
  via: nginx
  webroot: public
  xdebug: false
  cache: redis
  database: mariadb

services:
  database:
    type: mariadb:10.3
    user: mariadb
    password: mariadb
    database: plekapp
    portforward: 33066

    creds:
      user: mariadb
      password: mariadb
      database: plekapp

  appserver:
    run_as_root:
    - apt-get update -y
    - apt-get upgrade -y
    - docker-php-ext-install pcntl

